### ISSUE TITLE
Compare the HAND produced with HydroSAR and ASF-tools

### ISSUE THREAD

**Issue by cirrusasf** [fjmeyer/HydroSAR#4]
Hi, it is Jiang at ASF. We are investigating the HAND results produced by HydroSAR and ASF-tools. In ASF-tools, we calculate the HAND by applying whole geometries, not like you did in the HydroSAR, calculate every geometry in the geometries and fill the NAN pixels. It turns out that HAND by ASF-tools fills the NAN pixels with corresponding pixels in the dem. I would like to get your opinion about our method. I upload three files here. One is HAND_by_ASF, one HAND_by_HydroSAR, and difference between two HANDs. 

![Screenshot from 2022-04-06 14-39-48](https://user-images.githubusercontent.com/62269400/162099681-9841d5ee-eada-43a5-9bcd-2ade269865b5.png)
![Screenshot from 2022-04-06 14-32-59](https://user-images.githubusercontent.com/62269400/162099685-1247a911-2984-4ae3-993c-608ac9ebed6e.png)
![Screenshot from 2022-04-06 14-32-25](https://user-images.githubusercontent.com/62269400/162099689-4f289f29-e3d5-44b0-a679-942847cd0f7f.png)

**Comment by jhkennedy** [comment]
@cirrusasf , yes, `asf_tools` calculates HAND across the entire set of geometries passed in at once, not individual geometry by geometry.  

> It turns out that HAND by ASF-tools fills the NAN pixels with corresponding pixels in the dem.

We are absolutely **not** filling missing values from the DEM. Generally, since we're calculating across the entire geometry, we don't typically *see* NaN values produced inside convex hull surrounding the geometries. And if any NaN values are encountered inside the valid HAND geometry, we use the same `fill_nan` routine as HydroSAR. You can confirm this yourself by looking at the code here:
https://github.com/ASFHyP3/asf-tools/blob/develop/asf_tools/hand/calculate.py#L102-L108

The difference in strategy is entirely due to computational power -- HydroSAR, working in OpenSARlab, has much more limited processing capabilities than we have with HyP3, and so they often need to go geometry by geometry. We don't have that worry so we can correctly calculate across the entire area. 

For example, when we calculated the HAND globally, we calculated HAND over an area quadruple the size of each COP 30 DEM tile (buffering tile shape it by 1/2 width) to prevent any cut drainage basins inside the tile, and then clipped the HAND tile out of it.

---

Note: I'm currently on vacation, and not back until May 2nd, so I will be very slow to responding to this thread, if I do at all.

**Comment by cirrusasf** [comment]
From the three images I posted previous, we know that HAND images calculated by the  ASF-tools and the HydroSAR are different. The first image tells us where the difference are. It is that the river pixels and along the river pixels are different. The pixels of the HAND by ASF-tools have higher values than those by the HydroSAR.
